import 'dart:developer';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';

import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:quranvideo/provider/utils.dart';

saveSubtitleFile(BuildContext context) async {
  int currentTime = 0;
  String ayahSubTContent =
      "[Script Info]\n; Script generated by Aegisub 3.2.2\n; http://www.aegisub.org/\nTitle: Default Aegisub file\nScriptType: v4.00+\nWrapStyle: 0\nScaledBorderAndShadow: yes\nYCbCr Matrix: TV.601\nPlayResX: 700\nPlayResY: 1000\n\n[Aegisub Project Garbage]\nAudio File: ../test.mp4\nVideo File: ../test.mp4\nVideo AR Mode: 4\nVideo AR Value: 0.600000\nVideo Zoom Percent: 0.500000\nVideo Position: 108\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Poppins,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,40,40,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";
  // single subtitle structure. - Dialogue: 0,0:00:00.00,0:00:03.55,Default,,0,0,0,,{\\fad(1000,1000)\\pos(350,500)}{\\fnQCF2604}{\\fs60}ﱰ ﱱ ﱲ ﱳ ﱴ{\\fnFML-Leela\\fs28}\\N]dbpI: apjycpsS c£nXmhntmSv Rm³ {c&H00FFFF&}icWw tXSp¶p.{c}{\\fnPoppins\\fs16}\\N\\Nand from the evil of the women who blow on the knots,\n
  String translationSubTContent = "";

  var arabSubt = "";
  var engSubt = "";
  var localSubt = "";
  print(context.read<Utils>().ayahs.length);
  for (var i = 0; i < context.read<Utils>().ayahs.length; i++) {
    final ayahs = context.read<Utils>().ayahs;
    final ayahData = ayahs[i];

    print('MUBARAJK');
    int pagenum = ayahData.pageno;

    //============ GET COLOR
    Color ayahColor = context.read<Utils>().ayahColor;
    Color localColor = context.read<Utils>().localColor;
    Color engColor = context.read<Utils>().engColor;
    //============ GET FONT SIZE
    int ayahSize = context.read<Utils>().ayahFontSize;
    int localSize = context.read<Utils>().localFontSize;
    int engSize = context.read<Utils>().engFontSize;
    //============ GET ENABLED
    bool ayahEnable = context.read<Utils>().ayahEnable;
    bool engEnable = context.read<Utils>().engEnable;
    bool localEnable = context.read<Utils>().localEnable;
    // ======== POSITION
    int pos_x = context.read<Utils>().pos_x;
    int pos_y = context.read<Utils>().pos_y;

    String engFont = context.read<Utils>().engFontFamily!; //'Poppins';
    String localFont =
        context.read<Utils>().localFontFamily!; //'Noto Sans Malayalam Medium';

    String pageNo = "QCF2" + pagenum.toString().padLeft(3, '0');
    print('Page: $pageNo');

    if (ayahEnable) {
      // show arabic
      arabSubt =
          '{\\fn$pageNo}{\\fs$ayahSize}${formatColor(ayahColor)}${ayahData.glyph}';
      // arabSubt = '{\\fn${localFont}\\fs50}\\N\\N${ayahData.local}';
    }
    if (engEnable) {
      // show arabic
      engSubt =
          '{\\fn${engFont}\\fs$engSize}${formatColor(engColor)}\\N\\N${context.read<Utils>().cleanUpEngSubtitle(ayahData.eng!)}';
    }
    if (localEnable) {
      // show arabic
      localSubt =
          '{\\fn${localFont}\\fs$localSize}${formatColor(localColor)}\\N\\N${ayahData.local}';
    }

    print(currentTime.toString() +
        ' | ' +
        ayahData.endingTime.toString() +
        ' | ' +
        formatSubtitleDuration(ayahData.endingTime!) +
        ' | ' +
        formatSubtitleDuration(currentTime));
    var ayahSub =
        'Dialogue: 0,${formatSubtitleDuration(currentTime)},${formatSubtitleDuration(ayahData.endingTime!)},Default,,0,0,0,,{\\fad(200,200)\\pos($pos_x,$pos_y)}${arabSubt}${localSubt}${engSubt}\n';

    currentTime = ayahData.endingTime!;
    ayahSubTContent += ayahSub;
  }
  final dir = await getExternalStorageDirectory();
  final filename = dir!.path + '/subt.ass';
  await File(filename).writeAsString(ayahSubTContent);
  print('SUBTITLE GENERATED');
}

String formatSubtitleDuration(int milliseconds) {
  // '00:00:00.32'
  //
  //2304
  final tt = Duration(milliseconds: milliseconds);
  var res = tt.toString().substring(0, tt.toString().length - 4);
  res = res.padLeft(res.length + 1, '0');
  return res;
}

String? formatColor(Color color) {
  final c = color;

  final hex = c.toString().substring(10, 16);
  final r = hex[0] + hex[1];
  final g = hex[2] + hex[3];
  final b = hex[4] + hex[5];

  return ('{\\c&H$b$g$r&}');
}
